In [2]:
import pandas as pd
import json

In [3]:
with open('level1.json', 'r') as f:
    data = json.load(f)

df = pd.DataFrame(data['lessons'])

df

,id,title,content,examples
0,1,What is Python?,Python is a programming language used to write...,[print('Python is fun!')]
1,2,Printing Text,The print() function displays text or numbers ...,"[print('Hello, world!'), print('Welcome to Pyt..."
2,3,Comments,Comments are notes in your code that Python ig...,"[# This is a comment, print('Python ignores co..."
3,4,Running Python Code,"You can run Python code in an editor, a termin...","[print('This line runs first!'), print('Then t..."
4,5,Variables,Variables are used to store information. You c...,"[name = 'John', age = 21, print(name, age)]"
5,6,Rules for Variable Names,Variable names must start with a letter or und...,"[my_name = 'John', _count = 5, # my name = 'Jo..."
6,7,Data Types,"Common data types in Python are int (numbers),...","[age = 18, height = 5.9, name = 'Alex', is_stu..."
7,8,Printing Variables,You can print variables by including them in p...,"[name = 'John', print('Hello', name)]"
8,9,Type Checking,Use the type() function to check what data typ...,"[x = 10, print(type(x))]"
9,10,Numbers,Python can handle whole numbers (int) and deci...,"[a = 10 + 5, b = 3.2 * 2]"
10,11,Addition and Subtraction,Use + for addition and - for subtraction.,"[x = 5 + 3, y = 10 - 2]"
11,12,Multiplication and Division,Use * for multiplication and / for division. D...,"[x = 4 * 2, y = 9 / 3]"
12,13,Exponentiation,Use ** to raise a number to a power.,[x = 2 ** 3 # 2 to the power of 3]
13,14,Floor Division and Modulus,"// divides and rounds down, % gives the remain...","[print(7 // 2), print(7 % 2)]"
14,15,Strings,Strings are text in quotes. You can use single...,"[name = 'John', greeting = ""Hi there!""]"
15,16,Combining Strings,You can combine (concatenate) strings using +.,"[first = 'Hello', second = 'World', print(firs..."
16,17,String Repetition,Use * to repeat a string multiple times.,[print('Hi!' * 3)]
17,18,String Indexing,You can access characters in a string using sq...,"[word = 'Python', print(word[0]), print(word[-..."
18,19,String Slicing,You can get parts of a string using slicing: s...,"[word = 'Python', print(word[0:3])]"
19,20,String Methods,Strings have built-in methods to modify text l...,"[text = 'Hello', print(text.upper()), print(te..."
20,21,Getting User Input,Use input() to get data from the user. It alwa...,"[name = input('Enter your name: '), print('Hel..."
21,22,Type Conversion,"Convert data types using int(), float(), or st...","[age = int(input('Enter your age: ')), print(a..."
22,23,Booleans,Booleans represent True or False values.,"[is_sunny = True, is_raining = False]"
23,24,Comparison Operators,"You can compare values with ==, !=, >, <, >=, ...","[print(5 > 3), print(5 == 3)]"
24,25,Logical Operators,"and, or, and not combine or invert boolean val...","[x = 5, print(x > 0 and x < 10), print(not Fal..."
25,26,If Statements,If statements let you run code only when a con...,"[age = 18, if age >= 18:, print('Adult')]"
26,27,Else Statements,Else runs when the if condition is false.,"[age = 15, if age >= 18:, print('Adult'), ..."
27,28,Elif Statements,Elif checks additional conditions when the fir...,"[grade = 85, if grade >= 90:, print('A'), ..."
28,29,Indentation,Python uses indentation (spaces) to mark code ...,"[if True:, print('This line is indented')]"
29,30,Nested If Statements,You can put if statements inside other if stat...,"[x = 10, if x > 5:, if x < 15:, pr..."
30,31,While Loops,A while loop repeats code as long as a conditi...,"[count = 0, while count < 3:, print('Count..."
31,32,For Loops,A for loop is used to loop through a sequence ...,"[for i in range(5):, print(i)]"
32,33,Range Function,The range() function creates a sequence of num...,"[for num in range(3):, print(num), for num..."
33,34,Breaking Out of Loops,Use break to stop a loop early when a conditio...,"[for i in range(5):, if i == 3:, b..."
34,35,Skipping with Continue,Use continue to skip to the next iteration of ...,"[for i in range(5):, if i == 2:, c..."
35,36,Nested Loops,You can put one loop inside another loop. This...,"[for i in range(2):, for j in range(3):, ..."
36,37,Lists,Lists store multiple values in a single variab...,"[fruits = ['apple', 'banana', 'cherry'], print..."
37,38,Accessing List Elements,Access list elements using their index. Indexi...,"[numbers = [10, 20, 30], print(numbers[1])]"
38,39,Changing List Elements,You can change an item in a list by assigning ...,"[colors = ['red', 'blue', 'green'], colors[1] ..."
39,40,Looping Through Lists,Use a for loop to go through all items in a list.,"[animals = ['cat', 'dog', 'bird'], for a in an..."
40,41,List Methods,"Lists have useful methods like append(), remov...","[numbers = [3, 1, 4, 2], numbers.sort(), print..."
41,42,List Slicing,You can get a part of a list using slicing: li...,"[numbers = [0, 1, 2, 3, 4, 5], print(numbers[2..."
42,43,Tuples,"Tuples are like lists, but they cannot be chan...","[colors = ('red', 'blue', 'green'), print(colo..."
43,44,Dictionaries,Dictionaries store key-value pairs. You can us...,"[person = {'name': 'John', 'age': 21}, print(p..."
44,45,Adding and Changing Dictionary Items,You can add or modify dictionary values using ...,"[person = {'name': 'John', 'age': 21}, person[..."
45,46,Looping Through Dictionaries,"You can loop through keys, values, or both in ...","[person = {'name': 'John', 'age': 21}, for key..."
46,47,Sets,Sets store unique items and are unordered. The...,"[fruits = {'apple', 'banana', 'apple'}, print(..."
47,48,Adding and Removing from Sets,Use add() to add items and remove() to remove ...,"[colors = {'red', 'green'}, colors.add('blue')..."
48,49,Functions,Functions are reusable blocks of code that per...,"[def greet():, print('Hello!'), , greet()]"
49,50,Function Parameters,"Functions can take parameters, which are value...","[def greet(name):, print('Hello,', name), ..."
50,51,Return Values,Functions can return values using the return k...,"[def add(a, b):, return a + b, , result = ..."
51,52,Default Parameters,You can give function parameters default values.,"[def greet(name='friend'):, print('Hello,'..."
52,53,Scope of Variables,Variables created inside functions exist only ...,"[def example():, x = 5, print(x), , ex..."
53,54,Importing Modules,Modules are files that contain Python code you...,"[import math, print(math.sqrt(16))]"
54,55,Random Numbers,The random module can generate random numbers ...,"[import random, print(random.randint(1, 10)), ..."
55,56,Working with Strings and Numbers Together,"You can’t add strings and numbers directly, bu...","[age = 21, print('I am', age, 'years old.'), p..."
56,57,File Reading,Use open() and read() to read text from a file.,"[file = open('example.txt', 'r'), content = fi..."
57,58,File Writing,You can write to files using the 'w' mode with...,"[file = open('example.txt', 'w'), file.write('..."
58,59,With Statement for Files,Using with automatically closes the file when ...,"[with open('example.txt', 'r') as file:, p..."
59,60,Putting It All Together,"You can combine variables, loops, conditionals...","[def greet_users(users):, for name in user..."

In [6]:
df['text'] = (
    "Lesson " + df['id'].astype(str) + ": " + df['title'] + "\n\n" +
    df['content'] + "\n\nExamples:\n" + df['examples'].apply(lambda x: "\n".join(x))
)

df['text'][0]

"Lesson 1: What is Python?\n\nPython is a programming language used to write code that computers can understand. It is popular for being simple, readable, and powerful.\n\nExamples:\nprint('Python is fun!')"

In [8]:
df['text'] = df['text'].str.replace('\s+', ' ', regex=True).str.strip()
df['text'][0]

"Lesson 1: What is Python? Python is a programming language used to write code that computers can understand. It is popular for being simple, readable, and powerful. Examples: print('Python is fun!')"

In [11]:
df['topic'] = 'Python Basics'
df['difficulty'] = 'Beginner'
df['level'] = 1

In [13]:
df.to_csv('level1_clean.csv', index=False)

In [15]:
df['text'][0]

"Lesson 1: What is Python? Python is a programming language used to write code that computers can understand. It is popular for being simple, readable, and powerful. Examples: print('Python is fun!')"

In [16]:
df

,id,title,content,examples,text,topic,difficulty,level
0,1,What is Python?,Python is a programming language used to write...,[print('Python is fun!')],Lesson 1: What is Python? Python is a programm...,Python Basics,Beginner,1
1,2,Printing Text,The print() function displays text or numbers ...,"[print('Hello, world!'), print('Welcome to Pyt...",Lesson 2: Printing Text The print() function d...,Python Basics,Beginner,1
2,3,Comments,Comments are notes in your code that Python ig...,"[# This is a comment, print('Python ignores co...",Lesson 3: Comments Comments are notes in your ...,Python Basics,Beginner,1
3,4,Running Python Code,"You can run Python code in an editor, a termin...","[print('This line runs first!'), print('Then t...",Lesson 4: Running Python Code You can run Pyth...,Python Basics,Beginner,1
4,5,Variables,Variables are used to store information. You c...,"[name = 'John', age = 21, print(name, age)]",Lesson 5: Variables Variables are used to stor...,Python Basics,Beginner,1
5,6,Rules for Variable Names,Variable names must start with a letter or und...,"[my_name = 'John', _count = 5, # my name = 'Jo...",Lesson 6: Rules for Variable Names Variable na...,Python Basics,Beginner,1
6,7,Data Types,"Common data types in Python are int (numbers),...","[age = 18, height = 5.9, name = 'Alex', is_stu...",Lesson 7: Data Types Common data types in Pyth...,Python Basics,Beginner,1
7,8,Printing Variables,You can print variables by including them in p...,"[name = 'John', print('Hello', name)]",Lesson 8: Printing Variables You can print var...,Python Basics,Beginner,1
8,9,Type Checking,Use the type() function to check what data typ...,"[x = 10, print(type(x))]",Lesson 9: Type Checking Use the type() functio...,Python Basics,Beginner,1
9,10,Numbers,Python can handle whole numbers (int) and deci...,"[a = 10 + 5, b = 3.2 * 2]",Lesson 10: Numbers Python can handle whole num...,Python Basics,Beginner,1
10,11,Addition and Subtraction,Use + for addition and - for subtraction.,"[x = 5 + 3, y = 10 - 2]",Lesson 11: Addition and Subtraction Use + for ...,Python Basics,Beginner,1
11,12,Multiplication and Division,Use * for multiplication and / for division. D...,"[x = 4 * 2, y = 9 / 3]",Lesson 12: Multiplication and Division Use * f...,Python Basics,Beginner,1
12,13,Exponentiation,Use ** to raise a number to a power.,[x = 2 ** 3 # 2 to the power of 3],Lesson 13: Exponentiation Use ** to raise a nu...,Python Basics,Beginner,1
13,14,Floor Division and Modulus,"// divides and rounds down, % gives the remain...","[print(7 // 2), print(7 % 2)]",Lesson 14: Floor Division and Modulus // divid...,Python Basics,Beginner,1
14,15,Strings,Strings are text in quotes. You can use single...,"[name = 'John', greeting = ""Hi there!""]",Lesson 15: Strings Strings are text in quotes....,Python Basics,Beginner,1
15,16,Combining Strings,You can combine (concatenate) strings using +.,"[first = 'Hello', second = 'World', print(firs...",Lesson 16: Combining Strings You can combine (...,Python Basics,Beginner,1
16,17,String Repetition,Use * to repeat a string multiple times.,[print('Hi!' * 3)],Lesson 17: String Repetition Use * to repeat a...,Python Basics,Beginner,1
17,18,String Indexing,You can access characters in a string using sq...,"[word = 'Python', print(word[0]), print(word[-...",Lesson 18: String Indexing You can access char...,Python Basics,Beginner,1
18,19,String Slicing,You can get parts of a string using slicing: s...,"[word = 'Python', print(word[0:3])]",Lesson 19: String Slicing You can get parts of...,Python Basics,Beginner,1
19,20,String Methods,Strings have built-in methods to modify text l...,"[text = 'Hello', print(text.upper()), print(te...",Lesson 20: String Methods Strings have built-i...,Python Basics,Beginner,1
20,21,Getting User Input,Use input() to get data from the user. It alwa...,"[name = input('Enter your name: '), print('Hel...",Lesson 21: Getting User Input Use input() to g...,Python Basics,Beginner,1
21,22,Type Conversion,"Convert data types using int(), float(), or st...","[age = int(input('Enter your age: ')), print(a...",Lesson 22: Type Conversion Convert data types ...,Python Basics,Beginner,1
22,23,Booleans,Booleans represent True or False values.,"[is_sunny = True, is_raining = False]",Lesson 23: Booleans Booleans represent True or...,Python Basics,Beginner,1
23,24,Comparison Operators,"You can compare values with ==, !=, >, <, >=, ...","[print(5 > 3), print(5 == 3)]",Lesson 24: Comparison Operators You can compar...,Python Basics,Beginner,1
24,25,Logical Operators,"and, or, and not combine or invert boolean val...","[x = 5, print(x > 0 and x < 10), print(not Fal...","Lesson 25: Logical Operators and, or, and not ...",Python Basics,Beginner,1
25,26,If Statements,If statements let you run code only when a con...,"[age = 18, if age >= 18:, print('Adult')]",Lesson 26: If Statements If statements let you...,Python Basics,Beginner,1
26,27,Else Statements,Else runs when the if condition is false.,"[age = 15, if age >= 18:, print('Adult'), ...",Lesson 27: Else Statements Else runs when the ...,Python Basics,Beginner,1
27,28,Elif Statements,Elif checks additional conditions when the fir...,"[grade = 85, if grade >= 90:, print('A'), ...",Lesson 28: Elif Statements Elif checks additio...,Python Basics,Beginner,1
28,29,Indentation,Python uses indentation (spaces) to mark code ...,"[if True:, print('This line is indented')]",Lesson 29: Indentation Python uses indentation...,Python Basics,Beginner,1
29,30,Nested If Statements,You can put if statements inside other if stat...,"[x = 10, if x > 5:, if x < 15:, pr...",Lesson 30: Nested If Statements You can put if...,Python Basics,Beginner,1
30,31,While Loops,A while loop repeats code as long as a conditi...,"[count = 0, while count < 3:, print('Count...",Lesson 31: While Loops A while loop repeats co...,Python Basics,Beginner,1
31,32,For Loops,A for loop is used to loop through a sequence ...,"[for i in range(5):, print(i)]",Lesson 32: For Loops A for loop is used to loo...,Python Basics,Beginner,1
32,33,Range Function,The range() function creates a sequence of num...,"[for num in range(3):, print(num), for num...",Lesson 33: Range Function The range() function...,Python Basics,Beginner,1
33,34,Breaking Out of Loops,Use break to stop a loop early when a conditio...,"[for i in range(5):, if i == 3:, b...",Lesson 34: Breaking Out of Loops Use break to ...,Python Basics,Beginner,1
34,35,Skipping with Continue,Use continue to skip to the next iteration of ...,"[for i in range(5):, if i == 2:, c...",Lesson 35: Skipping with Continue Use continue...,Python Basics,Beginner,1
35,36,Nested Loops,You can put one loop inside another loop. This...,"[for i in range(2):, for j in range(3):, ...",Lesson 36: Nested Loops You can put one loop i...,Python Basics,Beginner,1
36,37,Lists,Lists store multiple values in a single variab...,"[fruits = ['apple', 'banana', 'cherry'], print...",Lesson 37: Lists Lists store multiple values i...,Python Basics,Beginner,1
37,38,Accessing List Elements,Access list elements using their index. Indexi...,"[numbers = [10, 20, 30], print(numbers[1])]",Lesson 38: Accessing List Elements Access list...,Python Basics,Beginner,1
38,39,Changing List Elements,You can change an item in a list by assigning ...,"[colors = ['red', 'blue', 'green'], colors[1] ...",Lesson 39: Changing List Elements You can chan...,Python Basics,Beginner,1
39,40,Looping Through Lists,Use a for loop to go through all items in a list.,"[animals = ['cat', 'dog', 'bird'], for a in an...",Lesson 40: Looping Through Lists Use a for loo...,Python Basics,Beginner,1
40,41,List Methods,"Lists have useful methods like append(), remov...","[numbers = [3, 1, 4, 2], numbers.sort(), print...",Lesson 41: List Methods Lists have useful meth...,Python Basics,Beginner,1
41,42,List Slicing,You can get a part of a list using slicing: li...,"[numbers = [0, 1, 2, 3, 4, 5], print(numbers[2...",Lesson 42: List Slicing You can get a part of ...,Python Basics,Beginner,1
42,43,Tuples,"Tuples are like lists, but they cannot be chan...","[colors = ('red', 'blue', 'green'), print(colo...","Lesson 43: Tuples Tuples are like lists, but t...",Python Basics,Beginner,1
43,44,Dictionaries,Dictionaries store key-value pairs. You can us...,"[person = {'name': 'John', 'age': 21}, print(p...",Lesson 44: Dictionaries Dictionaries store key...,Python Basics,Beginner,1
44,45,Adding and Changing Dictionary Items,You can add or modify dictionary values using ...,"[person = {'name': 'John', 'age': 21}, person[...",Lesson 45: Adding and Changing Dictionary Item...,Python Basics,Beginner,1
45,46,Looping Through Dictionaries,"You can loop through keys, values, or both in ...","[person = {'name': 'John', 'age': 21}, for key...",Lesson 46: Looping Through Dictionaries You ca...,Python Basics,Beginner,1
46,47,Sets,Sets store unique items and are unordered. The...,"[fruits = {'apple', 'banana', 'apple'}, print(...",Lesson 47: Sets Sets store unique items and ar...,Python Basics,Beginner,1
47,48,Adding and Removing from Sets,Use add() to add items and remove() to remove ...,"[colors = {'red', 'green'}, colors.add('blue')...",Lesson 48: Adding and Removing from Sets Use a...,Python Basics,Beginner,1
48,49,Functions,Functions are reusable blocks of code that per...,"[def greet():, print('Hello!'), , greet()]",Lesson 49: Functions Functions are reusable bl...,Python Basics,Beginner,1
49,50,Function Parameters,"Functions can take parameters, which are value...","[def greet(name):, print('Hello,', name), ...",Lesson 50: Function Parameters Functions can t...,Python Basics,Beginner,1
50,51,Return Values,Functions can return values using the return k...,"[def add(a, b):, return a + b, , result = ...",Lesson 51: Return Values Functions can return ...,Python Basics,Beginner,1
51,52,Default Parameters,You can give function parameters default values.,"[def greet(name='friend'):, print('Hello,'...",Lesson 52: Default Parameters You can give fun...,Python Basics,Beginner,1
52,53,Scope of Variables,Variables created inside functions exist only ...,"[def example():, x = 5, print(x), , ex...",Lesson 53: Scope of Variables Variables create...,Python Basics,Beginner,1
53,54,Importing Modules,Modules are files that contain Python code you...,"[import math, print(math.sqrt(16))]",Lesson 54: Importing Modules Modules are files...,Python Basics,Beginner,1
54,55,Random Numbers,The random module can generate random numbers ...,"[import random, print(random.randint(1, 10)), ...",Lesson 55: Random Numbers The random module ca...,Python Basics,Beginner,1
55,56,Working with Strings and Numbers Together,"You can’t add strings and numbers directly, bu...","[age = 21, print('I am', age, 'years old.'), p...",Lesson 56: Working with Strings and Numbers To...,Python Basics,Beginner,1
56,57,File Reading,Use open() and read() to read text from a file.,"[file = open('example.txt', 'r'), content = fi...",Lesson 57: File Reading Use open() and read() ...,Python Basics,Beginner,1
57,58,File Writing,You can write to files using the 'w' mode with...,"[file = open('example.txt', 'w'), file.write('...",Lesson 58: File Writing You can write to files...,Python Basics,Beginner,1
58,59,With Statement for Files,Using with automatically closes the file when ...,"[with open('example.txt', 'r') as file:, p...",Lesson 59: With Statement for Files Using with...,Python Basics,Beginner,1
59,60,Putting It All Together,"You can combine variables, loops, conditionals...","[def greet_users(users):, for name in user...",Lesson 60: Putting It All Together You can com...,Python Basics,Beginner,1